### ISSUE TITLE
Please submit more example images

### ISSUE THREAD

**Issue by deviantfero** [iotek/urnn#5]
Hi there! I was wondering if you could submit more examples of colorscheme generation by your script, maybe using a "color" display script?

**Comment by venam** [comment]
Hello there @deviantfero ,
Yes, I need to continue updating this project, adding more screenshots and colorschemes.

Not that many people helped, that's why I sorta left it a bit behind (for the moment).

That's a good idea to also show a color-script in the example screenshots.

**Comment by venam** [comment]
I just remembered that I opened a thread on the nixers.net forums with many screenshots:
Check it out: https://nixers.net/showthread.php?tid=1700

**Comment by deviantfero** [comment]
thanks for your reply! also I wanted you to checkout my project wich has an bjective much like your project, if you'd like to fork it to apply your color-generating script i would be so glad, or not. but check it out!

http://github.com/deviantfero/wpgtk

**Comment by venam** [comment]
The GUI for your software is very nice.
Our project is a neural network, it's not a color-generating script, it's more of an AI that _knows_ what colors will fit. That's how it differs from other color generators.

**Comment by neeasade** [comment]
> knows 

results vary(tm)

urnn needs a larger dataset and some tightening methinks. 

@venam can we consider like an albumify[1] or something?

[1] http://tudurom.github.io/albumify/

**Comment by venam** [comment]
Indeed, the dataset is very small but the results are quite good for such size.

Albumify the results?

If we could have an easier interface I think we'll get more help. A GUI or curses would be cool.

**Comment by neeasade** [comment]
> Albumify the results?

yeah, in the readme - that is, make a link to one instead of having all the pictures in a row right there.

> If we could have an easier interface I think we'll get more help.

true, the script is probably not very straightforward.

**Comment by venam** [comment]
@neeasade, Yes, we should make an album instead of having a stack of images in the README.md.
Let's just leave the best one as a display of what it is able to do.

We should think of what the user interaction will be like to add a new image to the set and test.

I'd personally do something like that:
At first the program asks questions such as:
- What the terminal emulator is in use
- Where the Xresources is (default ~/.Xresources)
- What the command to refresh the terminal color is (default xrdb -load Xresources location)
- What is the default image viewer (default xdg-open)
- What is the command to set the wallpaper

etc..
The configs will be set in a text file.

Then it's a prompt (REPL) with 2 or 3 commands:
`use <img>` #use the img as the image that the theme is based on
`retrain` #will retrain the network
`test` #will set the colors, use the img as background, and open the default terminal with a display color script
`keep` #will add the current colors and image to the set

For the tightening we need to play with the neural network parameters.

Just ideas that could help.
I think this project has potential.

**Comment by deviantfero** [comment]
I'm sorry to bother you with this, but i was planning to make a fork of my project [wpgtk](http://github.com/deviantfero/wpgtk) that utilizes urnn as a means to generate a colorscheme for the whole desktop environment, and given urnn's neural network nature, it would provide better results, but I'd like to know if it's ok with you, and what do I need to do in order for you to be ok with it.

thanks in advance!

**Comment by venam** [comment]
Yes, it would be great.
You'll have to add some buttons to your GUI to "retrain" the network and do other specific tasks related to URNN.

**Comment by deviantfero** [comment]
will do, and will keep you posted! thanks!

**Comment by neeasade** [comment]
@venam Alright, will consider that comment/feedback later -- I agree this project has potential, suppose we should do the thing (un-dead the project). 

@deviantfero swell, yo.

**Comment by deviantfero** [comment]
and just like that... [gurnnit](https://github.com/deviantfero/gurnnit) is born!, just writing this here to keep you posted, right now there's nothing of urnn in it, I will edit the README.md accordingly, i was thinking about using ImageMagick as a dependency to convert all image formats to png before going through urnn, and to create a button for feeding urnn's neural network with your instructions as a script

the name is not permanent, would appreciate your two cents on that too. thanks for everything, we'll be in touch! I will develop it slowly though, since i'm entering this year's first semester in a few days.

**Comment by venam** [comment]
@deviantfero You might want to incorporate other things from https://github.com/neeasade/autotheme.sh when you are at it.  
Remove the g in front of the name and I'm with it!

**Comment by deviantfero** [comment]
done! removed the g!

-- att. Fernando Vasquez --

2016-03-03 22:33 GMT-06:00 Patrick Louis notifications@github.com:
